name: sacco_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_textfield: ^1.0.8
  filter_list: ^1.0.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.2
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  lottie: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  syncfusion_flutter_datepicker: ^20.4.44

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/
